include ../Makefile.inc

GEN_EXE = t_uname

LINUX_EXE = procfs_pidmax procfs_user_exe

EXE = ${GEN_EXE} ${LINUX_EXE}

all : ${EXE}

allgen : ${GEN_EXE}

clean : 
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

${EXE} : ${LPLIB}		# True as a rough approximation
