env = Environment(CFLAGS='-g')

def make_prog(progname, cfile, **kwargs):
    env.Program(progname, cfile, LIBS=['proclib'], LIBPATH='.', **kwargs)

env.Library('proclib', ['proclib.c'])
make_prog('prog_proclist', 'proclist.c')
make_prog('prog_pstree', 'pstree.c')
make_prog('prog_sherlock', 'sherlock.c')
